spring:
  datasource:
    dynamic:
#      druid:
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        max-wait: 30000
#        connect-timeout: 6000
      primary: xcx01-admin #设置默认的数据源或者数据源组, 数据源不要带下划线！！！数据源不要带下划线！！！数据源不要带下划线！！！
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        xcx01-admin:
          # MySQL8
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/xcx01_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
#          type: com.alibaba.druid.pool.DruidDataSource
        xcx01:
          # MySQL8
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/xcx01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
#          type: com.alibaba.druid.pool.DruidDataSource
          # type: com.zaxxer.hikari.HikariDataSource
