server:
  port: 10067
  context-path: /
logging:
  config: classpath:logback-spring.xml

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: xcx01_admin_server
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xxx.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 结合logback输出到日志文件。日志等级为trace才能输出。要么自己实现一个类再用日志记录
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'xcx-admin'
      paths-to-match: '/**'
      packages-to-scan: com.xxx.xcx01
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn